"use client";
import { useData, Order } from "../context/DataContext";
import { useState, useEffect } from "react";

export default function AdminDashboardPage() {
    const { menus, orders, vouchers, contactMessages, isLoaded, updateOrderStatus, updatePaymentStatus, deleteOrder, addOrder } = useData();

    const [adminUsername, setAdminUsername] = useState("admin");
    const [adminPassword, setAdminPassword] = useState("admin");
    const [showPassword, setShowPassword] = useState(false);
    const [saveStatus, setSaveStatus] = useState("");

    const [currentTime, setCurrentTime] = useState(new Date());
    const [activePage, setActivePage] = useState(1);
    const [activeLimit, setActiveLimit] = useState(10);
    const [completedPage, setCompletedPage] = useState(1);
    const [completedLimit, setCompletedLimit] = useState(10);

    // Edit Modal State
    const [editingOrder, setEditingOrder] = useState<Order | null>(null);
    const [editStatus, setEditStatus] = useState<Order["status"]>("Baru");
    const [editPayment, setEditPayment] = useState<"Belum Lunas" | "Lunas">("Belum Lunas");

    // Create Modal State
    const [showCreateModal, setShowCreateModal] = useState(false);
    const [createCustomerName, setCreateCustomerName] = useState("");
    const [createTotalPrice, setCreateTotalPrice] = useState("");
    const [createStatus, setCreateStatus] = useState<Order["status"]>("Selesai");
    const [createPaymentStatus, setCreatePaymentStatus] = useState<"Belum Lunas" | "Lunas">("Lunas");

    useEffect(() => {
        const storedCreds = localStorage.getItem("adminCredentials");
        if (storedCreds) {
            const creds = JSON.parse(storedCreds);
            setAdminUsername(creds.username);
            setAdminPassword(creds.password);
        }
        
        const timer = setInterval(() => setCurrentTime(new Date()), 1000);
        return () => clearInterval(timer);
    }, []);

    const handleSaveAdmin = (e: React.FormEvent) => {
        e.preventDefault();
        localStorage.setItem("adminCredentials", JSON.stringify({ username: adminUsername, password: adminPassword }));
        setSaveStatus("Profil admin berhasil diperbarui!");
        setTimeout(() => setSaveStatus(""), 3000);
    };

    const handleExportCSV = () => {
        const headers = "ID,Tanggal,Nama Pelanggan,Status,Status Pembayaran,Total Harga,Detail Item\n";
        const rows = orders.map(o => {
            const itemsStr = o.items.map(i => `${i.qty}x ${i.name}`).join(" | ");
            return `"${o.id}","${new Date(o.createdAt).toLocaleString("id-ID")}","${o.customerName}","${o.status}","${o.paymentStatus || 'Belum Lunas'}","${o.totalPrice}","${itemsStr}"`;
        }).join("\n");
        
        const blob = new Blob([headers + rows], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);
        link.setAttribute("href", url);
        link.setAttribute("download", `Laporan_Pesanan_${new Date().toISOString().split('T')[0]}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const handleSaveEdit = async () => {
        if (editingOrder) {
            await updateOrderStatus(editingOrder.id, editStatus);
            await updatePaymentStatus(editingOrder.id, editPayment);
            setEditingOrder(null);
        }
    };
    
    const handleDelete = async (id: string) => {
        if (confirm("Yakin ingin menghapus pesanan ini? Aksi ini tidak dapat dibatalkan.")) {
            await deleteOrder(id);
        }
    };
    
    const handleCreateManual = async (e: React.FormEvent) => {
        e.preventDefault();
        await addOrder({
            id: "", // generated by backend
            customerName: createCustomerName,
            phone: "Manual",
            items: [{ product_id: 1, name: "Pesanan Manual Admin", qty: 1, subtotal: Number(createTotalPrice) }],
            totalPrice: Number(createTotalPrice),
            paymentMethod: "cash",
            status: createStatus,
            paymentStatus: createPaymentStatus,
            createdAt: new Date().toISOString()
        } as any);
        setShowCreateModal(false);
        setCreateCustomerName("");
        setCreateTotalPrice("");
    };

    if (!isLoaded) return <div className="p-8 text-center text-gray-500 dark:text-gray-400">Memuat data...</div>;

    const totalMenu = menus.length;
    
    const activeOrdersList = orders.filter(o => o.status === "Baru" || o.status === "Diproses");
    const completedOrdersList = orders.filter(o => o.status === "Selesai" || o.status === "Dibatalkan");

    const activeOrders = activeOrdersList.length;
    const completedOrders = completedOrdersList.length;
    const totalVouchers = vouchers.length;
    const newMessages = contactMessages.length;

    const totalActivePages = Math.ceil(activeOrders / activeLimit);
    const totalCompletedPages = Math.ceil(completedOrders / completedLimit);

    const displayedActiveOrders = activeOrdersList.slice((activePage - 1) * activeLimit, activePage * activeLimit);
    const displayedCompletedOrders = completedOrdersList.slice((completedPage - 1) * completedLimit, completedPage * completedLimit);

    return (
        <div className="space-y-6 relative">
            <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
                <div>
                    <h1 className="text-2xl font-black text-gray-900 dark:text-white">Ikhtisar Admin</h1>
                    <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">Ringkasan data aplikasi Sasa Kopi</p>
                </div>
                <div className="flex gap-2">
                    <button 
                        onClick={() => setShowCreateModal(true)}
                        className="bg-amber-600 hover:bg-amber-700 text-white text-sm font-bold py-2 px-4 rounded-xl transition-all shadow-sm"
                    >
                        + Tambah Pesanan
                    </button>
                    <button 
                        onClick={handleExportCSV}
                        className="bg-green-600 hover:bg-green-700 text-white text-sm font-bold py-2 px-4 rounded-xl transition-all shadow-sm flex items-center gap-2"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                        Ekspor CSV
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-white dark:bg-neutral-900 p-6 rounded-2xl border border-gray-200 dark:border-neutral-800 shadow-sm">
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400 mb-1">Total Menu</p>
                    <p className="text-3xl font-black text-amber-700 dark:text-amber-500">{totalMenu}</p>
                </div>
                <div className="bg-white dark:bg-neutral-900 p-6 rounded-2xl border border-gray-200 dark:border-neutral-800 shadow-sm">
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400 mb-1">Pesanan Aktif</p>
                    <p className="text-3xl font-black text-amber-700 dark:text-amber-500">{activeOrders}</p>
                </div>
                <div className="bg-white dark:bg-neutral-900 p-6 rounded-2xl border border-gray-200 dark:border-neutral-800 shadow-sm">
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400 mb-1">Pesanan Selesai</p>
                    <p className="text-3xl font-black text-green-600 dark:text-green-500">{completedOrders}</p>
                </div>
                <div className="bg-white dark:bg-neutral-900 p-6 rounded-2xl border border-gray-200 dark:border-neutral-800 shadow-sm">
                    <p className="text-sm font-semibold text-gray-500 dark:text-gray-400 mb-1">Pesan Kontak Baru</p>
                    <p className="text-3xl font-black text-blue-600 dark:text-blue-500">{newMessages}</p>
                </div>
            </div>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                
                {/* Active Orders List */}
                <div className="bg-white dark:bg-neutral-900 rounded-2xl border border-gray-200 dark:border-neutral-800 shadow-sm overflow-hidden flex flex-col">
                    <div className="p-4 bg-amber-50 dark:bg-amber-950/30 border-b border-gray-200 dark:border-neutral-800 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                        <div className="flex items-center gap-2">
                            <h2 className="text-lg font-bold text-amber-900 dark:text-amber-500">Pesanan Aktif</h2>
                            <span className="bg-amber-200 dark:bg-amber-900/50 text-amber-800 dark:text-amber-400 text-xs font-bold px-2 py-1 rounded-full">{activeOrders}</span>
                        </div>
                        <div className="flex items-center gap-3 text-sm">
                            <span className="text-amber-700 dark:text-amber-400 font-medium" suppressHydrationWarning>{currentTime.toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</span>
                            <select 
                                value={activeLimit} 
                                onChange={(e) => { setActiveLimit(Number(e.target.value)); setActivePage(1); }}
                                className="bg-white dark:bg-neutral-800 border border-amber-200 dark:border-neutral-700 rounded-lg px-2 py-1 text-xs focus:outline-none focus:ring-2 focus:ring-amber-500"
                            >
                                <option value={10}>10</option>
                                <option value={100}>100</option>
                                <option value={1000}>1000</option>
                            </select>
                        </div>
                    </div>
                    <div className="p-0 overflow-y-auto max-h-96">
                        {displayedActiveOrders.length === 0 ? (
                            <div className="p-8 text-center text-gray-500 dark:text-gray-400 text-sm">Belum ada pesanan aktif.</div>
                        ) : (
                            <ul className="divide-y divide-gray-100 dark:divide-neutral-800">
                                {displayedActiveOrders.map(order => (
                                    <li key={order.id} className="p-4 hover:bg-gray-50 dark:hover:bg-neutral-800 transition-colors">
                                        <div className="flex justify-between items-start mb-2">
                                            <div>
                                                <p className="font-bold text-gray-900 dark:text-white">{order.customerName}</p>
                                                <p className="text-xs text-gray-500 dark:text-gray-400" suppressHydrationWarning>{order.id} • {new Date(order.createdAt).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}</p>
                                            </div>
                                            <span className={`px-2 py-1 rounded-full text-xs font-bold ${order.status === "Baru" ? "bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400" : "bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400"}`}>
                                                {order.status}
                                            </span>
                                        </div>
                                        <div className="flex justify-between items-center mb-2">
                                            <p className="text-sm font-semibold text-amber-700 dark:text-amber-500">Rp {order.totalPrice.toLocaleString("id-ID")}</p>
                                            <span className={`px-2 py-1 rounded-full text-[10px] font-bold ${order.paymentStatus === "Lunas" ? "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400" : "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400"}`}>
                                                {order.paymentStatus || "Belum Lunas"}
                                            </span>
                                        </div>
                                        <div className="text-xs text-gray-600 dark:text-gray-400 line-clamp-2 mb-3">
                                            {order.items.map((item, i) => (
                                                <span key={i}>{item.qty}x {item.name}{i < order.items.length - 1 ? ", " : ""}</span>
                                            ))}
                                        </div>
                                        <div className="flex justify-end gap-2 mt-2 pt-2 border-t border-gray-100 dark:border-neutral-700">
                                            <button 
                                                onClick={() => { setEditingOrder(order); setEditStatus(order.status); setEditPayment(order.paymentStatus || "Belum Lunas"); }}
                                                className="text-xs font-semibold px-3 py-1 bg-gray-100 hover:bg-gray-200 dark:bg-neutral-700 dark:hover:bg-neutral-600 text-gray-700 dark:text-gray-300 rounded-lg transition-colors"
                                            >
                                                Edit
                                            </button>
                                            <button 
                                                onClick={() => handleDelete(order.id)}
                                                className="text-xs font-semibold px-3 py-1 bg-red-50 hover:bg-red-100 dark:bg-red-900/20 dark:hover:bg-red-900/40 text-red-600 dark:text-red-400 rounded-lg transition-colors"
                                            >
                                                Hapus
                                            </button>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>
                    {totalActivePages > 1 && (
                        <div className="p-3 border-t border-gray-200 dark:border-neutral-800 bg-gray-50 dark:bg-neutral-900/50 flex justify-between items-center text-sm">
                            <button 
                                onClick={() => setActivePage(p => Math.max(1, p - 1))}
                                disabled={activePage === 1}
                                className="px-3 py-1 bg-white dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-lg disabled:opacity-50 text-gray-700 dark:text-gray-300"
                            >
                                Prev
                            </button>
                            <span className="text-gray-600 dark:text-gray-400 text-xs">Halaman {activePage} dari {totalActivePages}</span>
                            <button 
                                onClick={() => setActivePage(p => Math.min(totalActivePages, p + 1))}
                                disabled={activePage === totalActivePages}
                                className="px-3 py-1 bg-white dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-lg disabled:opacity-50 text-gray-700 dark:text-gray-300"
                            >
                                Next
                            </button>
                        </div>
                    )}
                </div>

                {/* Completed Orders List */}
                <div className="bg-white dark:bg-neutral-900 rounded-2xl border border-gray-200 dark:border-neutral-800 shadow-sm overflow-hidden flex flex-col">
                    <div className="p-4 bg-green-50 dark:bg-green-950/30 border-b border-gray-200 dark:border-neutral-800 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                        <div className="flex items-center gap-2">
                            <h2 className="text-lg font-bold text-green-900 dark:text-green-500">Pesanan Selesai</h2>
                            <span className="bg-green-200 dark:bg-green-900/50 text-green-800 dark:text-green-400 text-xs font-bold px-2 py-1 rounded-full">{completedOrders}</span>
                        </div>
                        <div className="flex items-center gap-3 text-sm">
                            <span className="text-green-700 dark:text-green-400 font-medium" suppressHydrationWarning>{currentTime.toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</span>
                            <select 
                                value={completedLimit} 
                                onChange={(e) => { setCompletedLimit(Number(e.target.value)); setCompletedPage(1); }}
                                className="bg-white dark:bg-neutral-800 border border-green-200 dark:border-neutral-700 rounded-lg px-2 py-1 text-xs focus:outline-none focus:ring-2 focus:ring-green-500"
                            >
                                <option value={10}>10</option>
                                <option value={100}>100</option>
                                <option value={1000}>1000</option>
                            </select>
                        </div>
                    </div>
                    <div className="p-0 overflow-y-auto max-h-96">
                        {displayedCompletedOrders.length === 0 ? (
                            <div className="p-8 text-center text-gray-500 dark:text-gray-400 text-sm">Belum ada pesanan selesai.</div>
                        ) : (
                            <ul className="divide-y divide-gray-100 dark:divide-neutral-800">
                                {displayedCompletedOrders.map(order => (
                                    <li key={order.id} className="p-4 hover:bg-gray-50 dark:hover:bg-neutral-800 transition-colors opacity-75">
                                        <div className="flex justify-between items-start mb-2">
                                            <div>
                                                <p className="font-bold text-gray-700 dark:text-gray-200">{order.customerName}</p>
                                                <p className="text-xs text-gray-500 dark:text-gray-400" suppressHydrationWarning>{order.id} • {new Date(order.createdAt).toLocaleDateString("id-ID")}</p>
                                            </div>
                                            <span className={`px-2 py-1 rounded-full text-xs font-bold ${order.status === "Selesai" ? "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400" : "bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300"}`}>
                                                {order.status}
                                            </span>
                                        </div>
                                        <div className="flex justify-between items-center mb-2">
                                            <p className="text-sm font-semibold text-gray-700 dark:text-gray-300">Rp {order.totalPrice.toLocaleString("id-ID")}</p>
                                            <span className={`px-2 py-1 rounded-full text-[10px] font-bold ${order.paymentStatus === "Lunas" ? "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400" : "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400"}`}>
                                                {order.paymentStatus || "Belum Lunas"}
                                            </span>
                                        </div>
                                        <div className="text-xs text-gray-500 dark:text-gray-400 truncate mb-3">
                                            {order.items.map((item, i) => (
                                                <span key={i}>{item.qty}x {item.name}{i < order.items.length - 1 ? ", " : ""}</span>
                                            ))}
                                        </div>
                                        <div className="flex justify-end gap-2 mt-2 pt-2 border-t border-gray-100 dark:border-neutral-700">
                                            <button 
                                                onClick={() => { setEditingOrder(order); setEditStatus(order.status); setEditPayment(order.paymentStatus || "Belum Lunas"); }}
                                                className="text-xs font-semibold px-3 py-1 bg-gray-100 hover:bg-gray-200 dark:bg-neutral-700 dark:hover:bg-neutral-600 text-gray-700 dark:text-gray-300 rounded-lg transition-colors"
                                            >
                                                Edit
                                            </button>
                                            <button 
                                                onClick={() => handleDelete(order.id)}
                                                className="text-xs font-semibold px-3 py-1 bg-red-50 hover:bg-red-100 dark:bg-red-900/20 dark:hover:bg-red-900/40 text-red-600 dark:text-red-400 rounded-lg transition-colors"
                                            >
                                                Hapus
                                            </button>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>
                    {totalCompletedPages > 1 && (
                        <div className="p-3 border-t border-gray-200 dark:border-neutral-800 bg-gray-50 dark:bg-neutral-900/50 flex justify-between items-center text-sm">
                            <button 
                                onClick={() => setCompletedPage(p => Math.max(1, p - 1))}
                                disabled={completedPage === 1}
                                className="px-3 py-1 bg-white dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-lg disabled:opacity-50 text-gray-700 dark:text-gray-300"
                            >
                                Prev
                            </button>
                            <span className="text-gray-600 dark:text-gray-400 text-xs">Halaman {completedPage} dari {totalCompletedPages}</span>
                            <button 
                                onClick={() => setCompletedPage(p => Math.min(totalCompletedPages, p + 1))}
                                disabled={completedPage === totalCompletedPages}
                                className="px-3 py-1 bg-white dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-lg disabled:opacity-50 text-gray-700 dark:text-gray-300"
                            >
                                Next
                            </button>
                        </div>
                    )}
                </div>

            </div>

            {/* Edit Profil Admin Section */}
            <div className="bg-white dark:bg-neutral-900 rounded-2xl border border-gray-200 dark:border-neutral-800 shadow-sm overflow-hidden p-6 max-w-2xl">
                <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-1">Edit Profil Admin</h2>
                <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">Ubah username dan password untuk login admin.</p>
                
                {saveStatus && (
                    <div className="mb-4 p-3 bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-400 text-sm font-semibold rounded-xl border border-green-100 dark:border-green-900">
                        {saveStatus}
                    </div>
                )}

                <form onSubmit={handleSaveAdmin} className="space-y-4">
                    <div>
                        <label className="block text-sm font-semibold mb-1 text-gray-700 dark:text-gray-300">Username Admin</label>
                        <input 
                            required 
                            type="text" 
                            value={adminUsername} 
                            onChange={e => setAdminUsername(e.target.value)} 
                            className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white" 
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-semibold mb-1 text-gray-700 dark:text-gray-300">Password</label>
                        <div className="relative">
                            <input 
                                required 
                                type={showPassword ? "text" : "password"} 
                                value={adminPassword} 
                                onChange={e => setAdminPassword(e.target.value)} 
                                className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white pr-12" 
                            />
                            <button 
                                type="button" 
                                onClick={() => setShowPassword(!showPassword)}
                                className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                            >
                                {showPassword ? (
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg>
                                ) : (
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
                                )}
                            </button>
                        </div>
                    </div>
                    <button type="submit" className="bg-amber-600 hover:bg-amber-700 text-white font-bold py-3 px-6 rounded-xl transition-all shadow-md">
                        Simpan Perubahan
                    </button>
                </form>
            </div>

            {/* Modals */}
            {editingOrder && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
                    <div className="bg-white dark:bg-neutral-900 rounded-2xl w-full max-w-md shadow-2xl p-6 border border-gray-200 dark:border-neutral-800">
                        <h2 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">Edit Status Pesanan</h2>
                        <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">Pelanggan: <span className="font-semibold text-gray-900 dark:text-white">{editingOrder.customerName}</span></p>
                        
                        <div className="space-y-4 mb-6">
                            <div>
                                <label className="block text-sm font-semibold mb-2 text-gray-700 dark:text-gray-300">Status Pesanan</label>
                                <select 
                                    value={editStatus} 
                                    onChange={(e) => setEditStatus(e.target.value as any)}
                                    className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white"
                                >
                                    <option value="Baru">Baru</option>
                                    <option value="Diproses">Diproses</option>
                                    <option value="Selesai">Selesai</option>
                                    <option value="Dibatalkan">Dibatalkan</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-semibold mb-2 text-gray-700 dark:text-gray-300">Status Pembayaran</label>
                                <select 
                                    value={editPayment} 
                                    onChange={(e) => setEditPayment(e.target.value as any)}
                                    className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white"
                                >
                                    <option value="Belum Lunas">Belum Lunas</option>
                                    <option value="Lunas">Lunas</option>
                                </select>
                            </div>
                        </div>

                        <div className="flex gap-3 justify-end">
                            <button 
                                onClick={() => setEditingOrder(null)}
                                className="px-5 py-2.5 rounded-xl font-semibold text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-neutral-800 transition-colors"
                            >
                                Batal
                            </button>
                            <button 
                                onClick={handleSaveEdit}
                                className="px-5 py-2.5 rounded-xl font-bold bg-amber-600 hover:bg-amber-700 text-white shadow-md transition-colors"
                            >
                                Simpan
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {showCreateModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
                    <div className="bg-white dark:bg-neutral-900 rounded-2xl w-full max-w-md shadow-2xl p-6 border border-gray-200 dark:border-neutral-800">
                        <h2 className="text-xl font-bold mb-1 text-gray-900 dark:text-white">Tambah Pesanan Manual</h2>
                        <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">Tambahkan rekam pesanan secara manual ke dalam sistem.</p>
                        
                        <form onSubmit={handleCreateManual} className="space-y-4 mb-6">
                            <div>
                                <label className="block text-sm font-semibold mb-1 text-gray-700 dark:text-gray-300">Nama Pelanggan</label>
                                <input 
                                    required 
                                    type="text" 
                                    placeholder="Contoh: Budi"
                                    value={createCustomerName} 
                                    onChange={e => setCreateCustomerName(e.target.value)} 
                                    className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white" 
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-semibold mb-1 text-gray-700 dark:text-gray-300">Total Harga (Rp)</label>
                                <input 
                                    required 
                                    type="number" 
                                    min="0"
                                    placeholder="Contoh: 50000"
                                    value={createTotalPrice} 
                                    onChange={e => setCreateTotalPrice(e.target.value)} 
                                    className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white" 
                                />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-semibold mb-2 text-gray-700 dark:text-gray-300">Status Pesanan</label>
                                    <select 
                                        value={createStatus} 
                                        onChange={(e) => setCreateStatus(e.target.value as any)}
                                        className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white"
                                    >
                                        <option value="Baru">Baru</option>
                                        <option value="Diproses">Diproses</option>
                                        <option value="Selesai">Selesai</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-semibold mb-2 text-gray-700 dark:text-gray-300">Pembayaran</label>
                                    <select 
                                        value={createPaymentStatus} 
                                        onChange={(e) => setCreatePaymentStatus(e.target.value as any)}
                                        className="w-full bg-gray-50 dark:bg-neutral-800 border border-gray-200 dark:border-neutral-700 rounded-xl px-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-amber-500 text-gray-900 dark:text-white"
                                    >
                                        <option value="Lunas">Lunas</option>
                                        <option value="Belum Lunas">Belum Lunas</option>
                                    </select>
                                </div>
                            </div>
                            
                            <div className="flex gap-3 justify-end pt-2">
                                <button 
                                    type="button"
                                    onClick={() => setShowCreateModal(false)}
                                    className="px-5 py-2.5 rounded-xl font-semibold text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-neutral-800 transition-colors"
                                >
                                    Batal
                                </button>
                                <button 
                                    type="submit"
                                    className="px-5 py-2.5 rounded-xl font-bold bg-amber-600 hover:bg-amber-700 text-white shadow-md transition-colors"
                                >
                                    Simpan Pesanan
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
